### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by tasoss** [persianpros/dvbsnoop#8]
Hello.
I'm using ubuntu 16.04.
Trying to 'make' and i get

> make[2]: Entering directory '/root/la/dvbsnoop/src'
if gcc -DPACKAGE_NAME=\"dvbsnoop\" -DPACKAGE_TARNAME=\"dvbsnoop\" -DPACKAGE_VERSION=\"1.4.53\" -DPACKAGE_STRING=\"dvbsnoop\ 1.4.53\" -DPACKAGE_BUGREPORT=\"rasc@users.sourceforge.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LINUX_DVB_DMX_H=1 -I. -I. -I..    -g -O2 -MT dvbsnoop.o -MD -MP -MF ".deps/dvbsnoop.Tpo" -c -o dvbsnoop.o dvbsnoop.c; \
then mv -f ".deps/dvbsnoop.Tpo" ".deps/dvbsnoop.Po"; else rm -f ".deps/dvbsnoop.Tpo"; exit 1; fi
gcc  -g -O2   -o dvbsnoop  dvbsnoop.o ../src/dvb_api/libdvbapi.a ../src/pes/libpes.a ../src/sections/libsections.a ../src/ts/libts.a ../src/datacarousel/libdatacarousel.a ../src/tvanytime/libtvanytime.a ../src/testdata/libtestdata.a ../src/descriptors/libdescriptors.a ../src/private/libprivate.a ../src/private/default/libprivatedefault.a ../src/private/premiere.de/libprivatePremiereDE.a ../src/ebu/libebu.a ../src/net_ip/libnetip.a ../src/strings/libstrings.a ../src/misc/libmisc.a  
../src/private/libprivate.a(userdefs.o):(.data+0x18): undefined reference to `getPrivate_BskybUK'
collect2: error: ld returned 1 exit status
Makefile:268: recipe for target 'dvbsnoop' failed
make[2]: *** [dvbsnoop] Error 1
make[2]: Leaving directory '/root/la/dvbsnoop/src'
Makefile:348: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/la/dvbsnoop/src'
Makefile:188: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@devtrans:~/la/dvbsnoop# 

Any ideas please?
Thanks!

**Comment by persianpros** [comment]
Hi there,
No idea but maybe this could help you: https://github.com/OpenPLi/openpli-oe-core/blob/develop/meta-openpli/recipes-multimedia/dvbsnoop/dvbsnoop.bb

**Comment by tasoss** [comment]
Hello!
Thanks for replying.
Well i don't know how to use the bb file.I'm on a pc btw.
Could you please tell me if there is a version of dvbsnoop that is maintained?
Thanks!

**Comment by persianpros** [comment]
Our dvbsnoop is designed to be compiled with openembedded under Ubuntu 16.04.3 LTS and using Open PLi's OE: https://github.com/OpenPLi/openpli-oe-core
I can't help you anymore if you don't know how to compile an image with Open Embedded.

**Comment by tasoss** [comment]
Ok thank you!
